apiVersion: terra.terra-rebels.org/v1alpha1
kind: Relayer
metadata:
  name: relayer
spec:
  container:
    image: public.ecr.aws/classic-terra/relayer:alpine3.17
    imagePullPolicy: Always
  srcNetwork:
    networkName: atreides
    gasAdjustment: "1.5"
    gasPrices: 1uluna
    minGasAmount: "10000000"
    relayerKeyMnemonic: permit lava scene secret ball lava iron result reunion purpose sea badge focus rug cradle human plastic rough stand swarm pipe diagram deliver faculty
    coinType: "330"
  dstNetwork:
    networkName: harkonnen
    gasAdjustment: "1.5"
    gasPrices: 1uluna
    minGasAmount: "10000000"
    relayerKeyMnemonic: permit lava scene secret ball lava iron result reunion purpose sea badge focus rug cradle human plastic rough stand swarm pipe diagram deliver faculty
    coinType: "330"
