## Append samples you want in your CSV to this file as resources ##
resources:
- terra_v1alpha1_terradnode.yaml
- terra_v1alpha1_validator.yaml
- terra_v1alpha1_oraclefeeder.yaml
- terra_v1alpha1_indexernode.yaml
- terra_v1alpha1_relayer.yaml
- terra_v1alpha1_TerradNet.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
